# wrangler.toml for Cloudflare Pages (publish repo ROOT)
# Use this if your repo does NOT have a /public folder.
name = "chamberproject"
pages_build_output_dir = "."
compatibility_date = "2025-09-02"
